"""Cat last

Revision ID: 693a4c7a7da0
Revises: fba640d47024
Create Date: 2025-11-29 14:01:02.215561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693a4c7a7da0'
down_revision = 'fba640d47024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
