"""add product wrappers and weight fields

Revision ID: ebfe5ef56623
Revises: aa67f1b31833
Create Date: 2026-05-18 12:18:34.048499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfe5ef56623'
down_revision = 'aa67f1b31833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wrapper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_drafts_wrapper_id_product_wrappers'), 'product_wrappers', ['wrapper_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wrapper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_wrapper_id_product_wrappers'), 'product_wrappers', ['wrapper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_wrapper_id_product_wrappers'), type_='foreignkey')
        batch_op.drop_column('wrapper_id')
        batch_op.drop_column('weight')

    with op.batch_alter_table('product_drafts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_drafts_wrapper_id_product_wrappers'), type_='foreignkey')
        batch_op.drop_column('wrapper_id')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
